### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ghost** [xiaodong2008/xiaodong2008#1]
同为初中生
我本名 ⌈蒋添翼⌋
我初三了
看到了你的前端项目
我表示很赞
我还在成天当一个梦想家
可是你已经拿出了实绩
希望能和你合作 向你学习
请你加我的微信：Tianyi_Jiang
如果有Facebook：https://www.facebook.com/profile.php?id=100047590373722&mibextid=LQQJ4d
或者discord：Tianyi Jiang#0095
我们聊聊

**Comment by xiaodong2008** [comment]
微信找不到你，加了你的discord
